#!/bin/bash

function startnotrunning() {
	ps aux | grep $1 | head -n -2 | grep $1 || "$@" & 
}


startnotrunning thunderbird
startnotrunning firefox
startnotrunning todoist

lxappearance; sleep 1; pkill lxappearance