#!/bin/bash

function startnotrunning() {
	ps aux | grep $1 | head -n -2 | grep $1 || "$@" & 
}


startnotrunning todoist
startnotrunning thunderbird
startnotrunning firefox

lxappearance; sleep 0.5; pkill lxappearance